### ISSUE TITLE
Plans for supporting arrays of derived types

### ISSUE THREAD

**Issue by zhucaoxiang** [jameskermode/f90wrap#112] opened 2020-04-14 03:32 UTC
@jameskermode Hi James, do you have a clear schedule for implementing the feature of derived type arrays? 

I have a Fortran 90 code using allocatable derived types. So far, everything is working perfectly except for the derived type arrays. It would be really helpful if we have this new feature in the near future.

**Comment by jameskermode** [comment] 2020-04-14 08:53
There is already some support for arrays of derived type, see this (example)[https://github.com/jameskermode/f90wrap/tree/master/examples/arrayderivedtypes] and let me know where it falls short of what you need.

**Comment by zhucaoxiang** [comment] 2020-04-14 13:22
@jameskermode I saw this one. The one I mentioned is an array of allocated derived types, like the following
```
  type DegreeOfFreedom
     INTEGER              :: ND
     REAL   , allocatable :: xdof(:), xof(:,:), yof(:,:), zof(:,:)
  end type DegreeOfFreedom

  type(DegreeOfFreedom), allocatable :: DoF(:)
```

Right now, after wrapping using `f90wrapper`, I can access to the type `DegreeOfFreedom`, but I cannot access to the array `DoF`.

**Comment by zhucaoxiang** [comment] 2020-04-14 15:29
I have tested the derived arrays with fixed dimensions. I have a snippet of code like the following.
```
module test
  use globals, only : dp, zero
  implicit none

  type testsurface
  INTEGER              :: Nteta, Nzeta, Nfou=0, Nfp=0, NBnf=0
  REAL   , allocatable :: Rbc(:), Zbs(:), Rbs(:), Zbc(:), Bnc(:), Bns(:)
  REAL   , allocatable :: xx(:,:), yy(:,:), zz(:,:), nx(:,:), ny(:,:), nz(:,:), &
                          xt(:,:), yt(:,:), zt(:,:), xp(:,:), yp(:,:), zp(:,:), &
                          ds(:,:), bn(:,:), pb(:,:), &
                          Bx(:,:), By(:,:), Bz(:,:)
  INTEGER, allocatable :: bim(:), bin(:), Bnim(:), Bnin(:)
  REAL                 :: vol, area
end type testsurface


type testFreedom
  INTEGER              :: ND
  REAL   , allocatable :: xdof(:), xof(:,:), yof(:,:), zof(:,:)
end type testFreedom

  type(testsurface)     :: test_surf(10)
  type(testFreedom)  :: test_DoF(10)
  
end module test
```

After wrapping using `f90wrap`, I got everything compiled but I cannot find `test_surf` and `test_dof` in the module.
```
In [4]: dir(focus.test)                                                                                                  
Out[4]: 
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__metaclass__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_arrays',
 '_dt_array_initialisers',
 '_objs',
 'testFreedom',
 'testsurface']
```

By the way, I found that defining two derived types with the same name in two different modules is not allowed. I only did this (duplicate naming) when I am creating a test module.

**Comment by jameskermode** [comment] 2020-04-14 15:33
I think this should work fine, I'm using arrays of derived types in a number of projects. I'll see if I can reproduce and find what the problem is.

**Comment by jameskermode** [comment] 2020-04-14 15:44
I think I found the problem - module-level variables need the `target` attribute or they cannot be wrapped. a warning about this is printed:

```
UserWarning: removing test.test_surf as missing "target" attribute
UserWarning: removing test.test_dof as missing "target" attribute
```

**Comment by zhucaoxiang** [comment] 2020-04-14 15:46
@jameskermode But in the example, I didn't see explicit `target` attribute for the variables and they are still working.

**Comment by jameskermode** [comment] 2020-04-14 15:46
Changing to something like the following should solve the problem

```
  type(testsurface), target     :: test_surf(10)
  type(testFreedom), target  :: test_DoF(10)
```

**Comment by jameskermode** [comment] 2020-04-14 15:48
There are no module-level variables in the example; there one derived type is included within another. The requirement for `target` comes from the Fortran standard, which doesn't allow pointers to be directed at something which does not have it.

**Comment by zhucaoxiang** [comment] 2020-04-14 16:17
@jameskermode When I added the `target` attribute, I got a NameError. Here is using the example to reproduce the error.
```
module module_calcul
type type_ptmes
integer :: y
end type type_ptmes
type array_type
type(type_ptmes) :: x(2)
end type array_type

! new line I added 
type(array_type), target, dimension(10) :: test

contains
subroutine recup_point(x)
type(array_type) :: x
return
end subroutine recup_point
end module module_calcul
```

When testing, I got the following error.
```
python tests.py
Traceback (most recent call last):
  File "tests.py", line 23, in <module>
    import arrayderivedtype
  File "/Users/czhu/Documents/Code/f90wrap/examples/arrayderivedtypes/arrayderivedtype.py", line 182, in <module>
    module_calcul = Module_Calcul()
  File "//anaconda3/lib/python3.7/site-packages/f90wrap/fortrantype.py", line 53, in __init__
    init_array(self)
  File "/Users/czhu/Documents/Code/f90wrap/examples/arrayderivedtypes/arrayderivedtype.py", line 176, in init_array_test
    """, module_calcul.array_type)
NameError: name 'module_calcul' is not defined
make: *** [test] Error 1
```

**Comment by zhucaoxiang** [comment] 2020-04-17 19:24
@jameskermode For the [arrayderivedtypes](https://github.com/jameskermode/f90wrap/tree/master/examples/arrayderivedtypes) example, if I added the additional line like,
```
type(array_type), dimension(10) :: test
```
I will get warning of `UserWarning: removing module_calcul.test as missing "target" attribute`. But if I added the `target` attribute, like this,
```
type(array_type), target, dimension(10) :: test
```
I will get a NameError when importing the python package.
```
python tests.py
Traceback (most recent call last):
  File "tests.py", line 23, in <module>
    import arrayderivedtype
  File "/Users/czhu/Documents/Code/f90wrap/examples/arrayderivedtypes/arrayderivedtype.py", line 182, in <module>
    module_calcul = Module_Calcul()
  File "//anaconda3/lib/python3.7/site-packages/f90wrap/fortrantype.py", line 53, in __init__
    init_array(self)
  File "/Users/czhu/Documents/Code/f90wrap/examples/arrayderivedtypes/arrayderivedtype.py", line 176, in init_array_test
    """, module_calcul.array_type)
NameError: name 'module_calcul' is not defined
make: *** [test] Error 1
```

Do you have any clues?

**Comment by zhucaoxiang** [comment] 2020-05-18 15:31
@jameskermode Sorry for bugging you. I think I found the possible reason. The name `module_calcul` should be replaced by `Module_Calcul`, which is defined as a python class (`module_calcul` is the module name). I think there is a typo/bug when generating the python wrapper. It should be a quick fix.

**Comment by zhucaoxiang** [comment] 2020-06-02 19:22
@jameskermode There is an easy fix at here as well. There is a typo when generating the python class, as shown above. Right now, I just use a fix with `sed` to replace the wrong name after compilation.

**Comment by jameskermode** [comment] 2020-06-02 19:23
Do you know where the error is the code that generates the wrappers? Patch or pull request would be great!

**Comment by zhucaoxiang** [comment] 2020-06-02 19:35
I actually don't know the source code that generates the error. I can look it up. 

Meanwhile, let me describe what I have found.

When wrapping an array of derived types, like 

```
type(xtype), dimension(10), target :: xarr
```

 there is a mistake that happenes at the step of generating the final python class file `arrayderivedtype.py`. 

```python
    def init_array_xarr(self):
        self.xarr = f90wrap.runtime.FortranDerivedTypeArray(f90wrap.runtime.empty_type,
                                        _arrayderivedtype.f90wrap_module_calcul__array_getitem__xarr,
                                        _arrayderivedtype.f90wrap_module_calcul__array_setitem__xarr,
                                        _arrayderivedtype.f90wrap_module_calcul__array_len__xarr,
                                        """
        Element xarr ftype=type(xtype) pytype=Xtype
        
        
        Defined at test.fpp line 17
        
        """, module_calcul.xtype)
        return self.xarr
```
At the second last line, the name `module_calcul.xtype` should be replaced by `Module_Calcul.xtype`. `Module_Calcul` is defined ahead as a python class.

**Comment by zhucaoxiang** [comment] 2020-06-02 20:01
@jameskermode I found the source code error and fixed it. But I don't have the permission to create a pull request. Can you please give me write permission?

**Comment by jameskermode** [comment] 2020-06-02 20:10
Please make a fork and create the pull request from there.

**Comment by zhucaoxiang** [comment] 2020-06-02 20:17
@jameskermode Please check #116 . I didn't see any errors with the examples. Hopefully, I didn't import any new bugs.

**Comment by jameskermode** [comment] 2020-06-02 20:22
Closed by #116

**Closed by jameskermode** 2020-06-02 20:22 UTC

**Comment by currodri** [comment] 2024-04-28 16:45
It seems this feature fails when the array of derived types has a rank larger than 1.

**Comment by jameskermode** [comment] 2024-04-29 11:04
That's correct. A PR to extend to higher rank arrays of derived types would be welcome.
